name: Publish Package to npmjs
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      # Configure Git author information for the workflow
      - name: Set up Git
        run: |
          git config --global user.email "nitinjuyal1610@gmail.com"
          git config --global user.name "NitinJuyal1610"
          git config --global push.default simple
      - run: npm install
      - run: npm version patch
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
